import { h } from 'vue';

export interface ShortcutDef {
  id: string;
  action?: string;
  action2?: string;
  category: 'essentials' | 'format' | 'blocks' | 'edit' | 'view' | 'file' | 'tools';
  zh: string;
  en: string;
  winFallback: string;
  macFallback: string;
  tag?: string;
}

const CATEGORIES: { id: string; zh: string; en: string }[] = [
  { id: 'all', zh: '全部', en: 'All' },
  { id: 'essentials', zh: '常用高频', en: 'Essentials' },
  { id: 'format', zh: '排版格式', en: 'Typography' },
  { id: 'blocks', zh: '段落结构', en: 'Blocks & Tables' },
  { id: 'edit', zh: '编辑选择', en: 'Edit & Select' },
  { id: 'view', zh: '视图模式', en: 'View & Modes' },
  { id: 'file', zh: '文件标签', en: 'Files & Tabs' },
  { id: 'tools', zh: 'AI 与工具', en: 'AI & Tools' },
];

function renderCategoryIcon(id: string) {
  const icons: Record<string, () => any> = {
    all: () =>
      h('svg', { width: 12, height: 12, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }, [
        h('rect', { x: 3, y: 3, width: 7, height: 7, rx: 1 }),
        h('rect', { x: 14, y: 3, width: 7, height: 7, rx: 1 }),
        h('rect', { x: 14, y: 14, width: 7, height: 7, rx: 1 }),
        h('rect', { x: 3, y: 14, width: 7, height: 7, rx: 1 }),
      ]),
    essentials: () =>
      h('svg', { width: 12, height: 12, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }, [
        h('polygon', { points: '12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2' }),
      ]),
    format: () =>
      h('svg', { width: 12, height: 12, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }, [
        h('polyline', { points: '4 7 4 4 20 4 20 7' }),
        h('line', { x1: 9, y1: 20, x2: 15, y2: 20 }),
        h('line', { x1: 12, y1: 4, x2: 12, y2: 20 }),
      ]),
    blocks: () =>
      h('svg', { width: 12, height: 12, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }, [
        h('line', { x1: 21, y1: 6, x2: 3, y2: 6 }),
        h('line', { x1: 15, y1: 12, x2: 3, y2: 12 }),
        h('line', { x1: 17, y1: 18, x2: 3, y2: 18 }),
      ]),
    edit: () =>
      h('svg', { width: 12, height: 12, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }, [
        h('path', { d: 'M12 20h9' }),
        h('path', { d: 'M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z' }),
      ]),
    view: () =>
      h('svg', { width: 12, height: 12, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }, [
        h('path', { d: 'M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z' }),
        h('circle', { cx: 12, cy: 12, r: 3 }),
      ]),
    file: () =>
      h('svg', { width: 12, height: 12, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }, [
        h('path', { d: 'M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z' }),
      ]),
    tools: () =>
      h('svg', { width: 12, height: 12, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }, [
        h('path', { d: 'M12 3l1.912 5.813a2 2 0 0 0 1.275 1.275L21 12l-5.813 1.912a2 2 0 0 0-1.275 1.275L12 21l-1.912-5.813a2 2 0 0 0-1.275-1.275L3 12l5.813-1.912a2 2 0 0 0 1.275-1.275L12 3z' }),
      ]),
  };
  return (icons[id] || icons.all)();
}

const ALL_SHORTCUTS: ShortcutDef[] = [
  // ── 1. 常用高频 (Essentials) ──────────────────────────────────────────────
  {
    id: 'ess-save',
    action: 'file.save',
    category: 'essentials',
    zh: '保存当前文件',
    en: 'Save document',
    winFallback: 'Ctrl+S',
    macFallback: '⌘S',
    tag: 'Typora',
  },
  {
    id: 'ess-new',
    action: 'file.new',
    category: 'essentials',
    zh: '新建 Markdown 笔记',
    en: 'New note',
    winFallback: 'Ctrl+N',
    macFallback: '⌘N',
    tag: 'Typora',
  },
  {
    id: 'ess-open',
    action: 'file.open',
    category: 'essentials',
    zh: '打开文件',
    en: 'Open file',
    winFallback: 'Ctrl+O',
    macFallback: '⌘O',
    tag: 'Typora',
  },
  {
    id: 'ess-switcher',
    action: 'quickSwitcher.open',
    category: 'essentials',
    zh: '快速切换笔记',
    en: 'Quick file switcher',
    winFallback: 'Ctrl+P',
    macFallback: '⌘P',
    tag: 'Typora',
  },
  {
    id: 'ess-undo',
    category: 'essentials',
    zh: '撤销上一步',
    en: 'Undo',
    winFallback: 'Ctrl+Z',
    macFallback: '⌘Z',
    tag: 'Typora',
  },
  {
    id: 'ess-redo',
    category: 'essentials',
    zh: '重做操作',
    en: 'Redo',
    winFallback: 'Ctrl+Y / Ctrl+Shift+Z',
    macFallback: '⌘⇧Z',
    tag: 'Typora',
  },
  {
    id: 'ess-bold',
    action: 'format.bold',
    category: 'essentials',
    zh: '加粗文字',
    en: 'Bold text',
    winFallback: 'Ctrl+B',
    macFallback: '⌘B',
    tag: 'Typora',
  },
  {
    id: 'ess-italic',
    action: 'format.italic',
    category: 'essentials',
    zh: '斜体文字',
    en: 'Italic text',
    winFallback: 'Ctrl+I',
    macFallback: '⌘I',
    tag: 'Typora',
  },
  {
    id: 'ess-link',
    action: 'format.link',
    category: 'essentials',
    zh: '插入超链接',
    en: 'Insert link',
    winFallback: 'Ctrl+K',
    macFallback: '⌘K',
    tag: 'Typora',
  },
  {
    id: 'ess-table',
    action: 'format.table',
    category: 'essentials',
    zh: '插入就地表格',
    en: 'Insert table',
    winFallback: 'Ctrl+T',
    macFallback: '⌘⌥T',
    tag: 'Typora',
  },
  {
    id: 'ess-codeblock',
    action: 'format.codeBlock',
    category: 'essentials',
    zh: '插入代码块',
    en: 'Insert code block',
    winFallback: 'Ctrl+Shift+K',
    macFallback: '⌘⌥C',
    tag: 'Typora',
  },
  {
    id: 'ess-mathblock',
    action: 'format.mathBlock',
    category: 'essentials',
    zh: '插入数学公式块',
    en: 'Insert math block',
    winFallback: 'Ctrl+Shift+M',
    macFallback: '⌘⌥B',
    tag: 'Typora',
  },
  {
    id: 'ess-source-mode',
    action: 'view.toggleSourceMode',
    category: 'essentials',
    zh: '源码模式 / 实时预览',
    en: 'Toggle source mode / live preview',
    winFallback: 'Ctrl+/',
    macFallback: '⌘/',
    tag: 'Typora',
  },
  {
    id: 'ess-sidebar',
    action: 'view.toggleSidebar',
    category: 'essentials',
    zh: '切换侧边栏显隐',
    en: 'Toggle sidebar drawer',
    winFallback: 'Ctrl+Shift+L',
    macFallback: '⌘⇧L',
    tag: 'Typora',
  },
  {
    id: 'ess-agent',
    action: 'view.toggleAgentPanel',
    category: 'essentials',
    zh: '猫步 AI 助手',
    en: 'Toggle Catstep AI agent',
    winFallback: 'Ctrl+J / Ctrl+Shift+A',
    macFallback: '⌘J / ⌘⇧A',
    tag: '猫步 AI',
  },
  {
    id: 'ess-palette',
    action: 'palette.open',
    category: 'essentials',
    zh: '打开命令面板',
    en: 'Open command palette',
    winFallback: 'Ctrl+Shift+P / F1',
    macFallback: '⌘⇧P / F1',
    tag: 'Typora',
  },

  // ── 2. 排版与格式 (Typography & Formatting) ────────────────────────────────
  {
    id: 'fmt-h1',
    action: 'format.h1',
    category: 'format',
    zh: '1 级标题 (H1)',
    en: 'Heading 1',
    winFallback: 'Ctrl+1',
    macFallback: '⌘1',
    tag: 'Typora',
  },
  {
    id: 'fmt-h2',
    action: 'format.h2',
    category: 'format',
    zh: '2 级标题 (H2)',
    en: 'Heading 2',
    winFallback: 'Ctrl+2',
    macFallback: '⌘2',
    tag: 'Typora',
  },
  {
    id: 'fmt-h3',
    action: 'format.h3',
    category: 'format',
    zh: '3 级标题 (H3)',
    en: 'Heading 3',
    winFallback: 'Ctrl+3',
    macFallback: '⌘3',
    tag: 'Typora',
  },
  {
    id: 'fmt-h4',
    action: 'format.h4',
    category: 'format',
    zh: '4 级标题 (H4)',
    en: 'Heading 4',
    winFallback: 'Ctrl+4',
    macFallback: '⌘4',
    tag: 'Typora',
  },
  {
    id: 'fmt-h5',
    action: 'format.h5',
    category: 'format',
    zh: '5 级标题 (H5)',
    en: 'Heading 5',
    winFallback: 'Ctrl+5',
    macFallback: '⌘5',
    tag: 'Typora',
  },
  {
    id: 'fmt-h6',
    action: 'format.h6',
    category: 'format',
    zh: '6 级标题 (H6)',
    en: 'Heading 6',
    winFallback: 'Ctrl+6',
    macFallback: '⌘6',
    tag: 'Typora',
  },
  {
    id: 'fmt-p',
    action: 'format.paragraph',
    category: 'format',
    zh: '正文段落（清除标题）',
    en: 'Paragraph (Normal text)',
    winFallback: 'Ctrl+0',
    macFallback: '⌘0',
    tag: 'Typora',
  },
  {
    id: 'fmt-h-up',
    action: 'format.headingUp',
    category: 'format',
    zh: '提升标题级别 (H2 ➔ H1)',
    en: 'Increase heading level',
    winFallback: 'Ctrl+=',
    macFallback: '⌘=',
    tag: 'Typora',
  },
  {
    id: 'fmt-h-down',
    action: 'format.headingDown',
    category: 'format',
    zh: '降低标题级别 (H1 ➔ H2)',
    en: 'Decrease heading level',
    winFallback: 'Ctrl+-',
    macFallback: '⌘-',
    tag: 'Typora',
  },
  {
    id: 'fmt-bold',
    action: 'format.bold',
    category: 'format',
    zh: '加粗',
    en: 'Bold',
    winFallback: 'Ctrl+B',
    macFallback: '⌘B',
    tag: 'Typora',
  },
  {
    id: 'fmt-italic',
    action: 'format.italic',
    category: 'format',
    zh: '斜体',
    en: 'Italic',
    winFallback: 'Ctrl+I',
    macFallback: '⌘I',
    tag: 'Typora',
  },
  {
    id: 'fmt-underline',
    action: 'format.underline',
    category: 'format',
    zh: '下划线',
    en: 'Underline',
    winFallback: 'Ctrl+U',
    macFallback: '⌘U',
    tag: 'Typora',
  },
  {
    id: 'fmt-strike',
    action: 'format.strikethrough',
    category: 'format',
    zh: '删除线',
    en: 'Strikethrough',
    winFallback: 'Alt+Shift+5 / Ctrl+Shift+X',
    macFallback: '⌥⇧5 / ⌘⇧X',
    tag: 'Typora',
  },
  {
    id: 'fmt-code',
    action: 'format.inlineCode',
    category: 'format',
    zh: '行内代码',
    en: 'Inline code',
    winFallback: 'Ctrl+Shift+` / Ctrl+Alt+C',
    macFallback: '⌘⇧` / ⌘⌥C',
    tag: 'Typora',
  },
  {
    id: 'fmt-link',
    action: 'format.link',
    category: 'format',
    zh: '插入超链接',
    en: 'Insert link',
    winFallback: 'Ctrl+K',
    macFallback: '⌘K',
    tag: 'Typora',
  },
  {
    id: 'fmt-img',
    action: 'format.image',
    category: 'format',
    zh: '插入图片',
    en: 'Insert image',
    winFallback: 'Ctrl+Shift+I',
    macFallback: '⌘⇧I',
    tag: 'Typora',
  },
  {
    id: 'fmt-clear',
    action: 'format.clear',
    category: 'format',
    zh: '清除选中格式',
    en: 'Clear formatting',
    winFallback: 'Ctrl+\\',
    macFallback: '⌘\\',
    tag: 'Typora',
  },
  {
    id: 'fmt-highlight',
    action: 'format.highlight',
    category: 'format',
    zh: '文本高亮',
    en: 'Highlight text (==mark==)',
    winFallback: 'Ctrl+Shift+H',
    macFallback: '⌘⇧H',
    tag: 'GFM',
  },
  {
    id: 'fmt-prettier',
    action: 'format.markdown',
    category: 'format',
    zh: '美化格式化 Markdown',
    en: 'Prettier formatting',
    winFallback: 'Ctrl+Alt+L / Alt+Shift+F',
    macFallback: '⌘⌥L / ⌥⇧F',
    tag: 'Prettier',
  },

  // ── 3. 段落与结构 (Paragraphs & Blocks) ───────────────────────────────────
  {
    id: 'blk-table',
    action: 'format.table',
    category: 'blocks',
    zh: '插入就地交互表格',
    en: 'Insert interactive table',
    winFallback: 'Ctrl+T',
    macFallback: '⌘⌥T',
    tag: 'Typora',
  },
  {
    id: 'blk-codeblock',
    action: 'format.codeBlock',
    category: 'blocks',
    zh: '插入代码块',
    en: 'Insert code block',
    winFallback: 'Ctrl+Shift+K',
    macFallback: '⌘⌥C',
    tag: 'Typora',
  },
  {
    id: 'blk-mathblock',
    action: 'format.mathBlock',
    category: 'blocks',
    zh: '插入数学公式块',
    en: 'Insert math block (KaTeX)',
    winFallback: 'Ctrl+Shift+M',
    macFallback: '⌘⌥B',
    tag: 'Typora',
  },
  {
    id: 'blk-quote',
    action: 'format.quote',
    category: 'blocks',
    zh: '引用区块',
    en: 'Blockquote (> quote)',
    winFallback: 'Ctrl+Shift+Q',
    macFallback: '⌘⌥Q',
    tag: 'Typora',
  },
  {
    id: 'blk-ol',
    action: 'format.orderedList',
    category: 'blocks',
    zh: '有序数字列表',
    en: 'Ordered list (1. 2. 3.)',
    winFallback: 'Ctrl+Shift+[',
    macFallback: '⌘⌥O',
    tag: 'Typora',
  },
  {
    id: 'blk-ul',
    action: 'format.bulletList',
    category: 'blocks',
    zh: '无序圆点列表',
    en: 'Bullet list (- / *)',
    winFallback: 'Ctrl+Shift+]',
    macFallback: '⌘⌥U',
    tag: 'Typora',
  },
  {
    id: 'blk-task',
    action: 'format.taskList',
    category: 'blocks',
    zh: '任务待办列表',
    en: 'Task checkbox list (- [ ])',
    winFallback: 'Ctrl+Alt+X / Alt+Shift+X',
    macFallback: '⌘⌥X / ⌥⇧X',
    tag: 'Typora',
  },
  {
    id: 'blk-indent',
    category: 'blocks',
    zh: '增加缩进 (列表/正文)',
    en: 'Indent list or text',
    winFallback: 'Tab / Ctrl+]',
    macFallback: 'Tab / ⌘]',
    tag: 'Typora',
  },
  {
    id: 'blk-outdent',
    category: 'blocks',
    zh: '减少缩进 (列表/正文)',
    en: 'Outdent list or text',
    winFallback: 'Shift+Tab / Ctrl+[',
    macFallback: 'Shift+Tab / ⌘[',
    tag: 'Typora',
  },
  {
    id: 'blk-fold',
    action: 'fold.toggle',
    category: 'blocks',
    zh: '折叠 / 展开光标所在章节',
    en: 'Fold / unfold section at cursor',
    winFallback: 'Ctrl+Shift+[',
    macFallback: '⌘⇧[',
    tag: '折叠',
  },
  {
    id: 'blk-fold-all',
    action: 'fold.all',
    category: 'blocks',
    zh: '折叠文档所有章节',
    en: 'Fold all sections',
    winFallback: 'Ctrl+Alt+[',
    macFallback: '⌘⌥[',
    tag: '折叠',
  },
  {
    id: 'blk-unfold-all',
    action: 'fold.none',
    category: 'blocks',
    zh: '展开文档全部章节',
    en: 'Unfold all sections',
    winFallback: 'Ctrl+Alt+]',
    macFallback: '⌘⌥]',
    tag: '折叠',
  },

  // ── 4. 编辑与选择 (Edit & Selection) ───────────────────────────────────────
  {
    id: 'edt-sel-line',
    action: 'editor.selectLine',
    category: 'edit',
    zh: '选中当前整行 / 句子',
    en: 'Select line / sentence',
    winFallback: 'Ctrl+L',
    macFallback: '⌘L',
    tag: 'Typora',
  },
  {
    id: 'edt-sel-word',
    action: 'editor.selectWord',
    category: 'edit',
    zh: '选中当前光标词',
    en: 'Select current word',
    winFallback: 'Ctrl+D',
    macFallback: '⌘D',
    tag: 'Typora',
  },
  {
    id: 'edt-del-word',
    action: 'editor.deleteWord',
    category: 'edit',
    zh: '删除当前光标词',
    en: 'Delete current word',
    winFallback: 'Ctrl+Shift+D',
    macFallback: '⌘⇧D',
    tag: 'Typora',
  },
  {
    id: 'edt-del-line',
    category: 'edit',
    zh: '删除光标所在整行',
    en: 'Delete current line',
    winFallback: 'Ctrl+Shift+Backspace',
    macFallback: '⌘⇧⌫',
    tag: 'Typora',
  },
  {
    id: 'edt-sel-style',
    action: 'inbox.toggle',
    category: 'edit',
    zh: '选择样式范围 / 单元格',
    en: 'Select style range or cell',
    winFallback: 'Ctrl+E',
    macFallback: '⌘E',
    tag: 'Typora',
  },
  {
    id: 'edt-copy-md',
    action: 'export.copyMd',
    category: 'edit',
    zh: '复制为 Markdown',
    en: 'Copy as Markdown',
    winFallback: 'Ctrl+Shift+C',
    macFallback: '⌘⇧C',
    tag: 'Typora',
  },
  {
    id: 'edt-copy-html',
    action: 'export.copyHtml',
    category: 'edit',
    zh: '复制为富文本 HTML',
    en: 'Copy as rendered HTML',
    winFallback: 'Ctrl+Alt+Shift+C',
    macFallback: '⌘⌥⇧C',
    tag: '导出',
  },
  {
    id: 'edt-paste-plain',
    category: 'edit',
    zh: '粘贴为无格式纯文本',
    en: 'Paste as plain text',
    winFallback: 'Ctrl+Shift+V',
    macFallback: '⌘⇧V',
    tag: 'Typora',
  },
  {
    id: 'edt-sel-all',
    category: 'edit',
    zh: '全选文档内容',
    en: 'Select all',
    winFallback: 'Ctrl+A',
    macFallback: '⌘A',
    tag: 'Typora',
  },
  {
    id: 'edt-find',
    action: 'editor.find',
    category: 'edit',
    zh: '查找文本',
    en: 'Find text',
    winFallback: 'Ctrl+F',
    macFallback: '⌘F',
    tag: 'Typora',
  },
  {
    id: 'edt-find-next',
    category: 'edit',
    zh: '查找下一个匹配项',
    en: 'Find next match',
    winFallback: 'F3 / Enter',
    macFallback: '⌘G / Enter',
    tag: 'Typora',
  },
  {
    id: 'edt-find-prev',
    category: 'edit',
    zh: '查找上一个匹配项',
    en: 'Find previous match',
    winFallback: 'Shift+F3 / Shift+Enter',
    macFallback: '⌘⇧G / Shift+Enter',
    tag: 'Typora',
  },
  {
    id: 'edt-replace',
    action: 'editor.replace',
    category: 'edit',
    zh: '替换文本',
    en: 'Replace text',
    winFallback: 'Ctrl+H',
    macFallback: '⌘⌥F',
    tag: 'Typora',
  },
  {
    id: 'edt-case-cycle',
    action: 'editor.caseCycle',
    category: 'edit',
    zh: '英文大小写循环切换',
    en: 'Cycle case (Aa / AA / aa)',
    winFallback: 'Shift+F3',
    macFallback: '⇧F3',
    tag: '编辑',
  },
  {
    id: 'edt-cjk',
    action: 'proofread.cjk',
    category: 'edit',
    zh: '中英文排版规范校对',
    en: 'CJK typesetting proofread',
    winFallback: 'Ctrl+Shift+J / F6',
    macFallback: '⌘⇧J / F6',
    tag: '排版',
  },

  // ── 5. 视图与模式 (View & Modes) ──────────────────────────────────────────
  {
    id: 'view-source',
    action: 'view.toggleSourceMode',
    category: 'view',
    zh: '源码模式 / 实时预览',
    en: 'Toggle source mode / live preview',
    winFallback: 'Ctrl+/',
    macFallback: '⌘/',
    tag: 'Typora',
  },
  {
    id: 'view-sidebar',
    action: 'view.toggleSidebar',
    category: 'view',
    zh: '侧边栏抽屉显隐',
    en: 'Toggle sidebar drawer',
    winFallback: 'Ctrl+Shift+L',
    macFallback: '⌘⇧L',
    tag: 'Typora',
  },
  {
    id: 'view-outline',
    action: 'view.sidebarOutline',
    category: 'view',
    zh: '侧边栏：大纲目录树',
    en: 'Sidebar: Outline',
    winFallback: 'Ctrl+Shift+1',
    macFallback: '⌘⇧1',
    tag: 'Typora',
  },
  {
    id: 'view-files',
    action: 'view.sidebarFiles',
    category: 'view',
    zh: '侧边栏：文件目录列表',
    en: 'Sidebar: File tree',
    winFallback: 'Ctrl+Shift+2',
    macFallback: '⌘⇧2',
    tag: 'Typora',
  },
  {
    id: 'view-search',
    action: 'view.sidebarSearch',
    category: 'view',
    zh: '侧边栏：全文搜索面板',
    en: 'Sidebar: Global search',
    winFallback: 'Ctrl+Shift+3',
    macFallback: '⌘⇧3',
    tag: 'Typora',
  },
  {
    id: 'view-focus',
    action: 'view.toggleFocusMode',
    category: 'view',
    zh: '专注模式（光标段落聚焦）',
    en: 'Focus mode',
    winFallback: 'F8',
    macFallback: 'F8',
    tag: 'Typora',
  },
  {
    id: 'view-typewriter',
    action: 'view.toggleTypewriter',
    category: 'view',
    zh: '打字机模式（光标居中）',
    en: 'Typewriter mode',
    winFallback: 'F9',
    macFallback: 'F9',
    tag: 'Typora',
  },
  {
    id: 'view-fullscreen',
    action: 'view.toggleFullscreen',
    category: 'view',
    zh: '全屏模式',
    en: 'Toggle fullscreen',
    winFallback: 'F11 / Ctrl+Alt+F',
    macFallback: 'F11 / ⌘⌥F',
    tag: 'Typora',
  },
  {
    id: 'view-reading',
    action: 'view.toggleReading',
    category: 'view',
    zh: '纯净沉浸阅读模式',
    en: 'Distraction-free reading',
    winFallback: 'Ctrl+Shift+R',
    macFallback: '⌘⇧R',
    tag: '阅读',
  },
  {
    id: 'view-slideshow',
    action: 'view.slideshow',
    category: 'view',
    zh: '演示模式 (以 --- 分页)',
    en: 'Slideshow presentation',
    winFallback: 'Ctrl+Alt+P / F5',
    macFallback: '⌘⌥P / F5',
    tag: '演示',
  },
  {
    id: 'view-split-right',
    action: 'tile.splitRight',
    category: 'view',
    zh: '向右分屏对照阅读',
    en: 'Split editor pane right',
    winFallback: 'Ctrl+Alt+\\',
    macFallback: '⌘⌥\\',
    tag: '分屏',
  },
  {
    id: 'view-split-down',
    action: 'tile.splitDown',
    category: 'view',
    zh: '向下分屏对照阅读',
    en: 'Split editor pane down',
    winFallback: 'Ctrl+Shift+\\',
    macFallback: '⌘⇧\\',
    tag: '分屏',
  },
  {
    id: 'view-split-focus',
    action: 'tile.focusNext',
    action2: 'tile.focusPrev',
    category: 'view',
    zh: '切换下一 / 上一编辑器分屏',
    en: 'Focus next / prev editor pane',
    winFallback: 'Ctrl+Alt+→ / Ctrl+Alt+←',
    macFallback: '⌘⌥→ / ⌘⌥←',
    tag: '分屏',
  },

  // ── 6. 文件与标签 (Files & Tabs) ──────────────────────────────────────────
  {
    id: 'file-new',
    action: 'file.new',
    category: 'file',
    zh: '新建 Markdown 笔记',
    en: 'New markdown note',
    winFallback: 'Ctrl+N',
    macFallback: '⌘N',
    tag: 'Typora',
  },
  {
    id: 'file-new-txt',
    action: 'file.newText',
    category: 'file',
    zh: '新建纯文本文件 (.txt)',
    en: 'New plain text file',
    winFallback: 'Ctrl+Alt+N',
    macFallback: '⌘⌥N',
    tag: '文件',
  },
  {
    id: 'file-new-win',
    action: 'window.new',
    category: 'file',
    zh: '新建独立应用窗口',
    en: 'New standalone window',
    winFallback: 'Ctrl+Shift+N',
    macFallback: '⌘⇧N',
    tag: 'Typora',
  },
  {
    id: 'file-open',
    action: 'file.open',
    category: 'file',
    zh: '打开本地文件...',
    en: 'Open local file...',
    winFallback: 'Ctrl+O',
    macFallback: '⌘O',
    tag: 'Typora',
  },
  {
    id: 'file-import',
    action: 'file.import',
    category: 'file',
    zh: '导入外部文档...',
    en: 'Import external documents',
    winFallback: 'Ctrl+Alt+O',
    macFallback: '⌘⌥O',
    tag: 'Typora',
  },
  {
    id: 'file-save',
    action: 'file.save',
    category: 'file',
    zh: '保存当前修改',
    en: 'Save changes',
    winFallback: 'Ctrl+S',
    macFallback: '⌘S',
    tag: 'Typora',
  },
  {
    id: 'file-save-as',
    action: 'file.saveAs',
    category: 'file',
    zh: '文档另存为...',
    en: 'Save document as...',
    winFallback: 'Ctrl+Shift+S',
    macFallback: '⌘⇧S',
    tag: 'Typora',
  },
  {
    id: 'file-close-tab',
    action: 'file.closeTab',
    category: 'file',
    zh: '关闭当前标签页',
    en: 'Close current tab',
    winFallback: 'Ctrl+W',
    macFallback: '⌘W',
    tag: 'Typora',
  },
  {
    id: 'file-reopen-tab',
    action: 'tab.reopenClosed',
    category: 'file',
    zh: '重新打开关闭的标签页',
    en: 'Reopen closed tab',
    winFallback: 'Ctrl+Shift+T',
    macFallback: '⌘⇧T',
    tag: 'Typora',
  },
  {
    id: 'file-next-tab',
    action: 'tab.next',
    category: 'file',
    zh: '切换到下一个标签页',
    en: 'Switch to next tab',
    winFallback: 'Ctrl+Tab / Ctrl+]',
    macFallback: '⌃Tab / ⌘]',
    tag: '标签',
  },
  {
    id: 'file-prev-tab',
    action: 'tab.prev',
    category: 'file',
    zh: '切换到上一个标签页',
    en: 'Switch to previous tab',
    winFallback: 'Ctrl+Shift+Tab / Ctrl+[',
    macFallback: '⌃⇧Tab / ⌘[',
    tag: '标签',
  },
  {
    id: 'file-external',
    action: 'file.openExternal',
    category: 'file',
    zh: '外部编辑器打开',
    en: 'Open in external editor',
    winFallback: 'Ctrl+Shift+E',
    macFallback: '⌘⇧E',
    tag: '文件',
  },
  {
    id: 'file-pdf',
    action: 'export.pdfPrint',
    category: 'file',
    zh: '导出 PDF / 打印预览',
    en: 'Export PDF / print preview',
    winFallback: 'Ctrl+Alt+Shift+P',
    macFallback: '⌘⌥⇧P',
    tag: '导出',
  },

  // ── 7. 猫步 AI 与高效工具 (AI & Tools) ────────────────────────────────────
  {
    id: 'tool-agent',
    action: 'view.toggleAgentPanel',
    category: 'tools',
    zh: '猫步 AI 助手',
    en: 'Catstep AI assistant drawer',
    winFallback: 'Ctrl+J / Ctrl+Shift+A',
    macFallback: '⌘J / ⌘⇧A',
    tag: '猫步 AI',
  },
  {
    id: 'tool-rewrite',
    action: 'editor.aiRewrite',
    category: 'tools',
    zh: 'AI 悬浮改写与去 AI 味',
    en: 'AI rewrite selection',
    winFallback: 'Ctrl+Alt+J',
    macFallback: '⌘⌥J',
    tag: '猫步 AI',
  },
  {
    id: 'tool-palette',
    action: 'palette.open',
    category: 'tools',
    zh: '全局命令面板',
    en: 'Command palette (fuzzy search)',
    winFallback: 'Ctrl+Shift+P / F1',
    macFallback: '⌘⇧P / F1',
    tag: 'Typora',
  },
  {
    id: 'tool-switcher',
    action: 'quickSwitcher.open',
    category: 'tools',
    zh: '快速文件跳转 (VS Code 风格)',
    en: 'Quick file switcher',
    winFallback: 'Ctrl+P / Ctrl+Shift+O',
    macFallback: '⌘P / ⌘⇧O',
    tag: 'Typora',
  },
  {
    id: 'tool-search-global',
    action: 'search.global',
    category: 'tools',
    zh: '跨文件夹全文检索',
    en: 'Search in workspace folder',
    winFallback: 'Ctrl+Shift+F',
    macFallback: '⌘⇧F',
    tag: '搜索',
  },
  {
    id: 'tool-settings',
    action: 'settings.open',
    category: 'tools',
    zh: '偏好设置面板',
    en: 'Preferences & Settings',
    winFallback: 'Ctrl+,',
    macFallback: '⌘,',
    tag: 'Typora',
  },
  {
    id: 'tool-daily',
    action: 'daily.openToday',
    category: 'tools',
    zh: '打开今日随笔日记',
    en: "Open today's daily note",
    winFallback: 'Ctrl+Alt+D',
    macFallback: '⌘⌥D',
    tag: '日记',
  },
  {
    id: 'tool-pomodoro',
    action: 'pomodoro.startLast',
    category: 'tools',
    zh: '启动猫步专注',
    en: 'Start Pomodoro focus session',
    winFallback: 'Ctrl+Shift+Z',
    macFallback: '⌘⇧Z',
    tag: '专注',
  },
  {
    id: 'tool-table-nav',
    category: 'tools',
    zh: '表格键盘快捷导航',
    en: 'Next cell / Prev cell / Auto-add row',
    winFallback: 'Tab / Shift+Tab / Enter',
    macFallback: 'Tab / ⇧Tab / Enter',
    tag: '表格',
  },
  {
    id: 'tool-wikilink',
    category: 'tools',
    zh: '双链跳转',
    en: 'Hold modifier and click [[note]]',
    winFallback: 'Ctrl + 单击',
    macFallback: '⌘ + 单击',
    tag: '双链',
  },
];

export { CATEGORIES, renderCategoryIcon, ALL_SHORTCUTS };